projects:
  eq44:
    schemaPath: frontend/src/graphql/schema.json
    includes:
      - frontend/src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: frontend/src/API.ts
        docsFilePath: frontend/src/graphql
        maxDepth: 2
extensions:
  amplify:
    version: 3
